# config.yaml
reddit:
  client_id: 
  client_secret: 
  user_agent: reddit-probe:v0.1

probe:
  subreddit: "all"
  listing: "hot"
  time_filter: "day"
  post_limit: 10
  comment_sample: 5
  comment_replace_more_limit: 5
  qpm_cap: 90
  max_runtime_sec: 600
  raw_json: 1

supabase:
  enabled: 1
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  schema: "public"
