# config.yaml
reddit:
  client_id: 
  client_secret: 
  user_agent: ExpressWrangler4615:reddit-probe:v0.1 (by u/ExpressWrangler4615)

probe:
  subreddit: "all"
  listing: "hot"
  time_filter: "day"
  post_limit: 5
  comment_sample: 0
  comment_replace_more_limit: 1
  qpm_cap: 90
  max_runtime_sec: 600
  raw_json: 1
  out_dir: "./data"
  reports_dir: "./reports"

supabase:
  enabled: 1
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  schema: "public"
